### ISSUE TITLE
Internal Service Error 

### ISSUE THREAD

**Issue by IJEarleywine** [mjolnirdev/OpenPBP#1]
I am new to Rollbypost.com, and was creating a campaign. I saw a Github link below, and believe you are here to help. My problem is  I tried to a new campaign, but as I tried to click to continue I only got an Internal Server Error. I have tried from multiple computers with no change. I cannot delete the link, as I tried to create a second version of it, the same problem occurred. Can you help me?

**Comment by john-stone** [comment]
RollByPost.com is running demo for this project which reflects its current state which neither tested nor complete. I wouldn't count on it for your games. I've fixed the bug causing the error but I would expect there being more. 

https://github.com/mjolnirdev/OpenPBP/commit/349e536fea74991e67c8811e23140592c9fc5dde

**Comment by IJEarleywine** [comment]
Thanks John
